version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - seo-network

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - seo-network

volumes:
  db_data:

networks:
  seo-network:
